main/MainOrg/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/MainOrg/objects/CVSnapshot__c.object
<CustomObject>
    <fields>
        <fullName>Additional_info__c</fullName>
        <label>Additional info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>CVSnapshots</relationshipLabel>
        <relationshipName>CVSnapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Employement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ImageId__c</fullName>
        <label>ImageId</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CVSnapshot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVSnapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/MainOrg/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>CVSnapshot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CVSnapshot</label>
        <referenceTo>CVSnapshot__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Extend an Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/MainOrg/objects/OAuth_integration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>clientId__c</fullName>
        <label>clientId</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>clientSecret__c</fullName>
        <label>clientSecret</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>destURL__c</fullName>
        <label>destURL</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>OAuth_integration</label>
</CustomObject>

main/MainOrg/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External__c</fullName>
        <description>ID  of JobAdvertisement from Site/secondOrg</description>
        <externalId>true</externalId>
        <label>External</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Publication_Status__c</fullName>
        <label>Publication_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Not posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
	
    public static List <Job_Application__c> createJobApplications(Integer count){
        List <Job_Application__c> jobApplications = new List <Job_Application__c>();
        List <Candidate__c> candidates = createCandidates(count);
        List <Position__c> positions = createPositions(count);
        List <CVSnapshot__c> snapshots = createSnapshots(candidates);
        for(integer i = 0; i < count; i++){
            jobApplications.add( 
                new Job_Application__c( Position__c = positions[i].Id, Candidate__c = candidates[i].Id , CVSnapshot__c = snapshots[i].Id )
            );
        }
        insert jobApplications;
        return jobApplications;
    }

    public static List <Candidate__c> createCandidates(Integer count){
        List <Candidate__c> candidates = new List <Candidate__c>();
        for(integer i = 0; i < count; i++){
            candidates.add(
                new Candidate__c( First_Name__c = 'FirstName'+i, Last_Name__c = 'FirstName'+i ,
                                Email__c = i + 'ddddd134dd@gmail.com')
            );
        }
        insert candidates;
        return candidates;
    }
    public static List <Position__c> createPositions(Integer count){
        List <Position__c> positions = new List <Position__c>();
        for(integer i = 0; i < count; i++){
            positions.add(
                new Position__c( Name = 'Title'+i , external__c = 'someTestId' + i, 
                                Publication_Status__c ='Posted',
                               Status__c = 'Open', Approval_Status__c = 'Approved')
            );
        }
        insert positions;        
        return positions;
    }
    public static List <CVSnapshot__c> createSnapshots(List <Candidate__c> candidates){
        List <CVSnapshot__c> snapshots = new List <CVSnapshot__c>();
        for(Candidate__c candidate: candidates){
            snapshots.add(
                new CVSnapshot__c( Name = candidate.name , Email__c = candidate.Email__c, 
                                                       Phone__c = '09898989898', Age__c = '45',
                                                       Candidate__c = candidate.Id,
                                                       Additional_info__c = 'info' ,
                                                       ImageId__c = 'TESTimageID' , Salary__c = '550',
                                                       Employement__c = true 
                                                      )
            );
        }
        insert snapshots;        
        return snapshots;
    }
   
    public static List <Position__c> createUnclaimedPositions(Integer count){
        List <Position__c> unclaimedPositions = new List <Position__c>();        
        for(integer i = 0; i < count; i++){
            unclaimedPositions.add( 
                // Owner is an Admin (current user)
                new Position__c( Name = 'unclaimedPositionTest '+ i )
            );
        }
        insert unclaimedPositions;        
        return unclaimedPositions;
    }
    public static List <Position__c> createPositionsWithRecruiterOwner(Integer count){
        List <Position__c> createdPositions = new List <Position__c>();
        
        ID id = ReassignUnclaimedPositionToQueueService.getRecrutersIds()[0];
        for(integer i = 0; i < count; i++){
            createdPositions.add( 
                new Position__c( Name = 'createdByRecruiter '+ i , OwnerId = id)
            );
        }
        insert createdPositions;        
        return createdPositions;
    }
    public static void insertMockCustomSettings(){
        OAuth_integration__c settingsAPI = new OAuth_integration__c();
        settingsAPI.clientId__c = 'secretTest';
        settingsAPI.destURL__c = 'https://login.salesforce.com/services/oauth2/token';
        settingsAPI.clientSecret__c = 'secretTest';
        settingsAPI.username__c = 'secretTest';
        settingsAPI.password__c = 'secretTest';
        insert settingsAPI;
    }
    public static Integer generateRandomFromRange(integer startNum, integer endNum){
        Integer returnValue;
        //Logic- first we will generate random boolean value which will decide if we want to
        //add the random number from startNum or will subtract random number from endNum
        Integer randomNumber = Integer.valueof((math.random() * 10));
        boolean addSubFlag= math.mod(randomNumber,2) == 0 ? true : false;
        
        integer diffInRange = endNum-startNum;
        //Now find random number staring from 0 to diffInRange
        Integer randomNum = Math.mod(Math.round(Math.random()*diffInRange+1),diffInRange);
        
        //If addSubFlag is true, we will add random number generated between 0 and diffInRange from start number
        //else we will subtract random number from end number
                if(addSubFlag){
            if(diffInRange > 1)
                returnValue =startNum + randomNum;
            else
                returnValue =startNum;
        }else{
            if(diffInRange > 1)
                returnValue = endNum - randomNum;
            else
                returnValue =endNum;
        }
        return returnValue;
    }
    
    
}