main/MainOrg/objects/CVSnapshot__c.object
<CustomObject>
    <label>CVSnapshot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVSnapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/MainOrg/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>CVSnapshot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CVSnapshot</label>
        <referenceTo>CVSnapshot__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Extend an Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/MainOrg/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/MainOrg/classes/OnClosePositionTest.cls
@isTest
public class OnClosePositionTest {
	@isTest
    public static void onCloseUpdatePositionValidTest(){
        TestDataFactory.insertMockCustomSettings();
        List <Position__c> positions = TestDataFactory.createPositions(101);
        for(Position__c position: positions ){
            position.status__c = 'Closed' ;
        }
        Test.setMock(HttpCalloutMock.class, new MockAPICallerGenerator());
        Test.startTest();
        String msg;
        update positions;
        System.assertEquals( 0 , ApexPages.getMessages().size() );
        Test.stopTest();
    }
    @isTest
    public static void onCloseDeletePositionValidTest(){
        TestDataFactory.insertMockCustomSettings();
        List <Job_Application__c> jobs = TestDataFactory.createJobApplications(101);        
        Test.setMock(HttpCalloutMock.class, new MockAPICallerGenerator());
        Test.startTest();
        List <Position__c > positions = [SELECT ID FROM Position__c];
        String msg;
        delete positions;
        positions = [SELECT ID FROM Position__c];
        jobs = [SELECT ID FROM Job_Application__c];
        List<CVSnapshot__c> cvs = [SELECT ID FROM CVSnapshot__c];
        Test.stopTest();
        System.assertEquals( 0 , positions.size() );
        System.assertEquals( 0 , jobs.size() );
        System.assertEquals( 0 , cvs.size() );
         
    }
    @isTest
    public static void archivateJobAdvertisementsInvalidTest(){
        TestDataFactory.insertMockCustomSettings();
        List <Position__c> positions = TestDataFactory.createPositions(101);
        for(Position__c position: positions ){
            position.status__c = 'Closed' ;
        }
        Test.setMock(HttpCalloutMock.class, new MockAPICallerGeneratorInvalidStatus500());        
        Test.startTest();
        String msg;
        try{
            OnClosePositionHelper.archivateJobAdvertisements(positions);
        }catch(Exception e){
			msg = e.getMessage();            
        }
        System.assert( msg == null );
        Test.stopTest();       
    }
}