main/MainOrg/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External__c</fullName>
        <description>ID  of JobAdvertisement from Site/secondOrg</description>
        <externalId>true</externalId>
        <label>External</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publication_Status__c</fullName>
        <label>Publication_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Not posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salary_Range__c</fullName>
        <label>Salary Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>50K-75K</fullName>
                </value>
                <value>
                    <fullName>75K-90K</fullName>
                </value>
                <value>
                    <fullName>90K-120K</fullName>
                </value>
                <value>
                    <fullName>120K+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills_Required__c</fullName>
        <label>Skills Required</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAdvertisementController.cls
public class JobAdvertisementController {
    public APICaller api {get;set;}
    public boolean connected {get;set;}
    public JobAdvertisementsWrapper currentJA {get;set;}
    public Position__c position {get;set;}
    
    public JobAdvertisementController(){
        ID currentRecordId =  ApexPages.currentPage().getParameters().get('id');
        fetchPosition(currentRecordId);
    }
    public void fetchPosition(ID positionID){
        try{
            this.position = [SELECT ID, External__c, Education__c, Hiring_Manager__c,
                             Hiring_Manager__r.Phone, Job_Description__c, Publication_Status__c,
                             Hiring_Manager__r.Email , Hiring_Manager__r.Name,Salary_Range__c,
                             Name , Status__c, Location__c , Approval_Status__c,Skills_Required__c
                            FROM Position__c WHERE id=:positionID LIMIT 1];    
        }catch(QueryException e){
            sendError(System.Label.PositionFetchingException + ' ' + e);
        }
    }
    public void postAdvertisement(){
        api = new APICaller();
        login();
        JobAdvertisementsWrapper wrappedPosition = JobAdvertisementsWrapper.convertPosition(position);        
        String externalId = createJobAdvertisement(wrappedPosition);
        if(externalId != null ){
            position.External__c = externalId ;
            position.Publication_Status__c = 'Posted';
            update position;
            sendInfo(System.Label.Position_successfully_posted);
        }
    }
    public void updateAdvertisement(){
        api = new APICaller();
        login();
        fetchPosition(position.id);
        JobAdvertisementsWrapper wrappedPosition = JobAdvertisementsWrapper.convertPosition(position);
        updateJobAdvertisement(wrappedPosition);
    }
    public void removeAdvertisement(){
        api = new APICaller();
        login();
        deleteJobAdvertisementById(position.External__c);
    }
    public void login(){
        try{
        	api.oauthLogin();
        	connected = api.oauth != null ? true : false ;
        }catch(Task6Exception e){
            System.debug('Task6Exception e : ' + e);
            sendError('Connection failed');
            connected = false;
        }
    }
    public void deleteJobAdvertisementById(String externalId){
        try{
            api.deleteJobAdvertisementById( externalId ) ;
            sendInfo('Deleted Successfully');
            if(position.External__c != null ){
                position.External__c = null ;
                position.Publication_Status__c = 'Not posted';
                update position;
            }
        }catch(Task6Exception e){
            System.debug('Task6Exception e : ' + e.getMessage());
            sendError(e.getMessage());
        }
    }
    public String createJobAdvertisement(JobAdvertisementsWrapper wrappedPosition){
        try{
            return api.createJobAdvertisement(wrappedPosition) ;
        }catch(Task6Exception e){
            System.debug('Task6Exception e : ' + e.getMessage());
            sendError(e.getMessage());
            return null;
        }
        
    }
    public void updateJobAdvertisement(JobAdvertisementsWrapper wrappedPosition){
        String resultMsg;
        try{
            api.updateJobAdvertisement(wrappedPosition) ;
            System.debug(System.Label.JobAdveirtesement_successfully_updated);
            sendInfo(System.Label.JobAdveirtesement_successfully_updated);
        }catch(Task6Exception e){
            System.debug('Task6Exception e : ' + e.getMessage());
            sendError(e.getMessage());
        }        
    }
    public void sendError(String msg){
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, msg));
    }
    public void sendInfo(String msg){
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, msg));
    }
    
    
    public void getJobAdvertisementById(String checkedRecord){
        api = new APICaller();
        login();
        try{
            this.currentJA = api.getJobAdvertisementById(checkedRecord) ; 
            sendInfo('Selected successfully');
        }catch(Task6Exception e){
            System.debug('Task6Exception e : ' + e.getMessage());
            sendError(System.Label.Server_Exception);
        }             
    }
    
}