main/MainOrg/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External__c</fullName>
        <description>ID  of JobAdvertisement from Site/secondOrg</description>
        <externalId>true</externalId>
        <label>External</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salary_Range__c</fullName>
        <label>Salary Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>50K-75K</fullName>
                </value>
                <value>
                    <fullName>75K-90K</fullName>
                </value>
                <value>
                    <fullName>90K-120K</fullName>
                </value>
                <value>
                    <fullName>120K+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills_Required__c</fullName>
        <label>Skills Required</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAdvertisementsWrapper.cls
public class JobAdvertisementsWrapper {
    public String salary {get;set;}
    public String salaryMax {get;set;}
    public String salaryMin {get;set;}
    public String email {get;set;}
    public String phone {get;set;}
    public String status {get;set;}
    //current id => externalId => JobAdvertisement__c.Id
    public String id {get;set;}
    public String name {get;set;}
    public String skills {get;set;}
    public String description {get;set;}
    public String manager_name {get;set;}
    public String education {get;set;}
    public String location {get;set;}
    
    public static JobAdvertisementsWrapper convertPosition(Position__c position){        
        JobAdvertisementsWrapper result = new JobAdvertisementsWrapper();
        fillSalaryRange(result, position);
        result.location = position.Location__c;
        result.education = position.Education__c;
        result.email = position.Hiring_Manager__r.Email;
        result.phone = position.Hiring_Manager__r.Phone;
        result.name = position.Name;
        result.status = position.Status__c;
        result.manager_name = position.Hiring_Manager__r.Name;
        result.description = position.Job_Description__c;
        result.skills = position.Skills_Required__c;
        result.id = position.External__c;
        return result ;
    }
    public static void fillSalaryRange(JobAdvertisementsWrapper result ,Position__c position){
        if(position.Salary_Range__c != null && position.Salary_Range__c != ''){
            List <Integer> values = reformSalaryRange(position.Salary_Range__c);           
            if(values.size()> 0){
                result.salaryMin = values[0] + '';
                if(values.size() == 2){
                    result.salaryMax = values[1] + '';
                }
            }
        }
    }
    public static List <Integer> reformSalaryRange(String salaryRange){
        List <String> levels = salaryRange.split('K');
        List <Integer> values = new List <Integer>();
        for(String level: levels){
            String stringLevel = '';
            for(integer i =0; i <level.length();i++){
                String currentChar = level.mid(i,1);
                if(currentChar.isNumeric()){
                    stringLevel += currentChar;
                }
            }if(stringLevel.length() > 0){
                values.add( integer.valueof(stringLevel) );
            }
        }
        return values;
    }
}